import PropTypes from 'prop-types'

export const propTypes = {
  autoHeight: PropTypes.bool,
  children: PropTypes.array,
  duration: PropTypes.number,
  fadeOutAnimation: PropTypes.bool,
  infinite: PropTypes.bool,
  isRTL: PropTypes.bool,
  items: PropTypes.array,
  keysControlDisabled: PropTypes.bool,
  mouseTrackingEnabled: PropTypes.bool,
  onInitialized: PropTypes.func,
  onResized: PropTypes.func,
  onSlideChange: PropTypes.func,
  onSlideChanged: PropTypes.func,
  preventEventOnTouchMove: PropTypes.bool,
  responsive: PropTypes.object,
  shouldHandleResizeEvent: PropTypes.func,
  showSlideInfo: PropTypes.bool,
  slideToIndex: PropTypes.number,
  stagePadding: PropTypes.object,
  startIndex: PropTypes.number,
  swipeDelta: PropTypes.number,
  swipeDisabled: PropTypes.bool,
  touchTrackingEnabled: PropTypes.bool,
  transitionTimingFunction: PropTypes.string,
}

export const defaultProps = {
  autoHeight: false,
  children: [],
  duration: 250,
  fadeOutAnimation: false,
  infinite: true,
  isRTL: false,
  items: [],
  keysControlDisabled: false,
  mouseTrackingEnabled: false,
  preservePosition: false,
  preventEventOnTouchMove: false,
  responsive: {},
  showSlideInfo: false,
  slideToIndex: 0,
  stagePadding: {},
  startIndex: 0,
  swipeDisabled: false,
  swipeDelta: 10,
  touchTrackingEnabled: true,
  transitionTimingFunction: 'ease-out',
}
